include:
  remote: "https://github.com/git-developer/docker-support/raw/v3.2.1/gitlab-ci/docker-support.yml"

variables:
  UPDATE_CHECK_URLS: 'https://github.com/baycom/tfrec.git'

stages:
- post_checkout

trigger_on_update:
  extends: .docker_support:.trigger_on_update
  stage: post_checkout
  dependencies: []

run_matrix_build:
  extends: .docker_support:.build_job
  stage: post_checkout
  trigger:
    include: .build.yml
    forward:
      pipeline_variables: true
  parallel:
    matrix:
      - BASE_IMAGE:      [ "debian:stable-slim", "debian:oldstable-slim" ]
        BUILD_ARGS:      "BASE_IMAGE"
        BUILD_CONTEXT:   "image"
        IMAGE_PLATFORMS: 'linux/amd64,linux/i386,linux/arm64/v8,linux/arm/v7'
